import os
import secrets
import sqlite3
import json
import hashlib
import hmac
import base64
from datetime import datetime, timedelta, timezone
from urllib.parse import urlencode
from urllib.error import HTTPError, URLError
from urllib.request import Request as UrlRequest, urlopen
from functools import wraps
from openai import OpenAI
from flask import Flask, abort, flash, redirect, render_template, request, session, url_for
from werkzeug.middleware.proxy_fix import ProxyFix
from werkzeug.security import check_password_hash, generate_password_hash

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "autoengineer.db")
DATABASE_URL = os.environ.get("DATABASE_URL", "")
PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY", "")
PAYSTACK_BASE_URL = "https://api.paystack.co"
# =========================
# OPENAI AI CUSTOMER CARE
# =========================
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-5.5")

openai_client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.environ.get("TWILIO_FROM_NUMBER", "")
IDENTITY_VERIFICATION_URL = os.environ.get("IDENTITY_VERIFICATION_URL", "")
IDENTITY_API_KEY = os.environ.get("IDENTITY_API_KEY", "")
PREMIUM_PAYSTACK_PLAN_CODES = {
    "weekly": os.environ.get("PAYSTACK_PREMIUM_WEEKLY_PLAN", ""),
    "monthly": os.environ.get("PAYSTACK_PREMIUM_MONTHLY_PLAN", ""),
    "annual": os.environ.get("PAYSTACK_PREMIUM_ANNUAL_PLAN", ""),
}
PREMIUM_PLANS = {
    "weekly": {"label": "Weekly", "amount": 3000, "days": 7},
    "monthly": {"label": "Monthly", "amount": 9000, "days": 30},
    "annual": {"label": "Annual", "amount": 45000, "days": 365},
}

app = Flask(__name__, template_folder="templates", static_folder="static")
app.secret_key = os.environ.get("FLASK_SECRET_KEY", "dev-only-change-this-secret")
if os.environ.get("FLASK_ENV") == "production" and app.secret_key == "dev-only-change-this-secret":
    raise RuntimeError("FLASK_SECRET_KEY must be configured in production")
app.config.update(
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE="Lax",
    SESSION_COOKIE_SECURE=os.environ.get("FLASK_ENV") == "production",
    PERMANENT_SESSION_LIFETIME=timedelta(days=30),
)
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)


@app.after_request
def add_security_headers(response):
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    response.headers.setdefault("Permissions-Policy", "geolocation=(self)")
    if os.environ.get("FLASK_ENV") == "production":
        response.headers.setdefault("Strict-Transport-Security", "max-age=31536000; includeSubDomains")
    return response


def get_db():
    if DATABASE_URL.startswith(("postgres://", "postgresql://")):
        import psycopg
        from psycopg.rows import dict_row

        return PostgresConnection(psycopg.connect(DATABASE_URL, row_factory=dict_row))

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


class PostgresConnection:
    def __init__(self, connection):
        self.connection = connection

    def __enter__(self):
        return self

    def __exit__(self, exception_type, exception_value, traceback):
        if exception_type:
            self.connection.rollback()
        else:
            self.connection.commit()
        self.connection.close()

def execute(self, query, parameters=()):
    stripped_query = query.strip()

    if stripped_query.upper().startswith("PRAGMA TABLE_INFO"):
        table_name = stripped_query.split("(")[1].split(")")[0].strip()

        query = """
            SELECT column_name AS name
            FROM information_schema.columns
            WHERE table_name = %s
            ORDER BY ordinal_position
        """

        return self.connection.execute(query, (table_name,))

    query = query.replace("?", "%s")

    query = query.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )

    if "INSERT OR IGNORE INTO " in query.upper():
        query = query.replace(
            "INSERT OR IGNORE INTO ",
            "INSERT INTO ",
            1
        )
        query = f"{query.rstrip().rstrip(';')} ON CONFLICT DO NOTHING"

    return self.connection.execute(query, parameters)

    def executemany(self, query, parameters):
        query = query.replace("?", "%s")
        query = query.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        )

        if "INSERT OR IGNORE INTO " in query.upper():
            query = query.replace(
                "INSERT OR IGNORE INTO ",
                "INSERT INTO ",
                1
            )
            query = f"{query.rstrip().rstrip(';')} ON CONFLICT DO NOTHING"

        return self.connection.executemany(query, parameters)

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()


def init_db():
    with get_db() as conn:
                if not DATABASE_URL.startswith(("postgres://", "postgresql://")):
            conn.execute("PRAGMA foreign_keys = ON")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                email TEXT UNIQUE NOT NULL,
                phone TEXT,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL CHECK(role IN ('customer', 'engineer')),
                location TEXT,
                car_model TEXT,
                specialization TEXT,
                experience TEXT,
                bio TEXT DEFAULT '',
                verified INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )         
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ai_chat_messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                session_id TEXT NOT NULL,
                role TEXT NOT NULL,
                body TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """
        )
        service_request_columns = {
            row[1] if isinstance(row, sqlite3.Row) else row["name"]
            for row in conn.execute(
                "PRAGMA table_info(service_requests)"
            ).fetchall()
        }
        for column, definition in {
            "customer_lat": "REAL",
            "customer_lng": "REAL",
            "engineer_lat": "REAL",
            "engineer_lng": "REAL",
            "location_updated_at": "TIMESTAMP",
        }.items():
            if column not in service_request_columns:
                conn.execute(f"ALTER TABLE service_requests ADD COLUMN {column} {definition}")

        user_columns = {
            row[1] if isinstance(row, sqlite3.Row) else row["name"]
            for row in conn.execute("PRAGMA table_info(users)").fetchall()
        }
        added_verification_column = "verified" not in user_columns
        if added_verification_column:
            conn.execute("ALTER TABLE users ADD COLUMN verified INTEGER NOT NULL DEFAULT 0")
        if "referral_code" not in user_columns:
            conn.execute("ALTER TABLE users ADD COLUMN referral_code TEXT")
        if "referred_by" not in user_columns:
            conn.execute("ALTER TABLE users ADD COLUMN referred_by INTEGER")

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS wallets (
                user_id INTEGER PRIMARY KEY,
                balance INTEGER NOT NULL DEFAULT 0,
                login_bonus_claimed INTEGER NOT NULL DEFAULT 0,
                FOREIGN KEY(user_id) REFERENCES users(id)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS withdrawals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                amount INTEGER NOT NULL,
                account_name TEXT NOT NULL,
                account_number TEXT NOT NULL,
                bank_name TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(user_id) REFERENCES users(id)
            )
            """
        )
        if not DATABASE_URL.startswith(("postgres://", "postgresql://")):
            conn.execute("PRAGMA foreign_keys = ON")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS quotes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                request_id INTEGER NOT NULL,
                engineer_id INTEGER NOT NULL,
                customer_id INTEGER NOT NULL,
                amount INTEGER NOT NULL,
                notes TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(request_id) REFERENCES service_requests(id)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS reviews (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                request_id INTEGER NOT NULL,
                reviewer_id INTEGER NOT NULL,
                reviewee_id INTEGER NOT NULL,
                rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
                comment TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS refund_requests (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                request_id INTEGER NOT NULL,
                customer_id INTEGER NOT NULL,
                amount INTEGER NOT NULL,
                reason TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS payments (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                request_id INTEGER NOT NULL,
                customer_id INTEGER NOT NULL,
                engineer_id INTEGER NOT NULL,
                amount INTEGER NOT NULL,
                commission INTEGER NOT NULL DEFAULT 0,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        payment_columns = {
            row[1] if isinstance(row, sqlite3.Row) else row["name"]
            for row in conn.execute("PRAGMA table_info(payments)").fetchall()
        }
        if "reference" not in payment_columns:
            conn.execute("ALTER TABLE payments ADD COLUMN reference TEXT")
        if "channel" not in payment_columns:
            conn.execute("ALTER TABLE payments ADD COLUMN channel TEXT")
        if "provider" not in payment_columns:
            conn.execute("ALTER TABLE payments ADD COLUMN provider TEXT DEFAULT 'paystack'")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS disputes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                request_id INTEGER NOT NULL,
                opened_by INTEGER NOT NULL,
                reason TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'open',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                request_id INTEGER NOT NULL,
                sender_id INTEGER NOT NULL,
                recipient_id INTEGER NOT NULL,
                body TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS trust_checks (
                user_id INTEGER PRIMARY KEY,
                identity_status TEXT NOT NULL DEFAULT 'pending',
                phone_status TEXT NOT NULL DEFAULT 'pending',
                nin_status TEXT NOT NULL DEFAULT 'pending',
                bvn_status TEXT NOT NULL DEFAULT 'pending',
                nin_last4 TEXT,
                bvn_last4 TEXT,
                otp_hash TEXT,
                otp_expires_at TEXT,
                otp_attempts INTEGER NOT NULL DEFAULT 0,
                duplicate_flag INTEGER NOT NULL DEFAULT 0,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        trust_columns = {
            row[1] if isinstance(row, sqlite3.Row) else row["name"]
            for row in (
                conn.execute("PRAGMA table_info(trust_checks)").fetchall()
                if isinstance(conn, sqlite3.Connection)
                else conn.execute(
                    "SELECT column_name AS name FROM information_schema.columns WHERE table_name = 'trust_checks'"
                ).fetchall()
            )
        }
        trust_migrations = {
            "nin_status": "TEXT NOT NULL DEFAULT 'pending'",
            "bvn_status": "TEXT NOT NULL DEFAULT 'pending'",
            "nin_last4": "TEXT",
            "bvn_last4": "TEXT",
            "otp_hash": "TEXT",
            "otp_expires_at": "TEXT",
            "otp_attempts": "INTEGER NOT NULL DEFAULT 0",
        }
        for column, definition in trust_migrations.items():
            if column not in trust_columns:
                conn.execute(f"ALTER TABLE trust_checks ADD COLUMN {column} {definition}")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS subscriptions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                engineer_id INTEGER NOT NULL,
                plan TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'active',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        subscription_columns = {
            row[1] if isinstance(row, sqlite3.Row) else row["name"]
            for row in conn.execute(
                "PRAGMA table_info(subscriptions)"
            ).fetchall()
        }
        subscription_migrations = {
            "billing_cycle": "TEXT NOT NULL DEFAULT 'monthly'",
            "amount": "INTEGER NOT NULL DEFAULT 0",
            "reference": "TEXT",
            "provider": "TEXT DEFAULT 'paystack'",
            "paid_at": "TIMESTAMP",
            "expires_at": "TIMESTAMP",
        }
        for column, definition in subscription_migrations.items():
            if column not in subscription_columns:
                conn.execute(f"ALTER TABLE subscriptions ADD COLUMN {column} {definition}")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS fleet_accounts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                owner_id INTEGER NOT NULL,
                company_name TEXT NOT NULL,
                vehicles INTEGER NOT NULL,
                status TEXT NOT NULL DEFAULT 'lead',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS fraud_flags (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                reason TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'open',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS car_catalog (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                make TEXT NOT NULL,
                model TEXT NOT NULL,
                year_range TEXT NOT NULL,
                body_type TEXT NOT NULL,
                fuel_type TEXT NOT NULL,
                popular INTEGER NOT NULL DEFAULT 0,
                UNIQUE(make, model)
            )
            """
        )
        car_catalog = [
            ("Toyota", "Corolla", "2014-2025", "Sedan", "Petrol", 1),
            ("Toyota", "Camry", "2012-2025", "Sedan", "Petrol / Hybrid", 1),
            ("Toyota", "RAV4", "2013-2025", "SUV", "Petrol / Hybrid", 1),
            ("Toyota", "Hilux", "2012-2025", "Pickup", "Diesel", 1),
            ("Honda", "Civic", "2012-2025", "Sedan", "Petrol", 1),
            ("Honda", "Accord", "2011-2024", "Sedan", "Petrol", 1),
            ("Honda", "CR-V", "2013-2025", "SUV", "Petrol / Hybrid", 1),
            ("Hyundai", "Elantra", "2012-2025", "Sedan", "Petrol", 1),
            ("Hyundai", "Tucson", "2013-2025", "SUV", "Petrol / Hybrid", 1),
            ("Kia", "Sportage", "2012-2025", "SUV", "Petrol / Diesel", 1),
            ("Kia", "Sorento", "2012-2025", "SUV", "Petrol / Diesel", 0),
            ("Ford", "Ranger", "2012-2025", "Pickup", "Diesel", 1),
            ("Ford", "Escape", "2013-2024", "SUV", "Petrol / Hybrid", 0),
            ("Mercedes-Benz", "C-Class", "2012-2025", "Sedan", "Petrol / Hybrid", 0),
            ("Mercedes-Benz", "GLC", "2016-2025", "SUV", "Petrol / Hybrid", 0),
            ("BMW", "3 Series", "2012-2025", "Sedan", "Petrol / Diesel", 0),
            ("BMW", "X3", "2012-2025", "SUV", "Petrol / Diesel", 0),
            ("Volkswagen", "Golf", "2012-2025", "Hatchback", "Petrol / Diesel", 0),
            ("Volkswagen", "Tiguan", "2012-2025", "SUV", "Petrol / Diesel", 0),
            ("Nissan", "Altima", "2013-2024", "Sedan", "Petrol", 0),
            ("Nissan", "X-Trail", "2014-2025", "SUV", "Petrol / Hybrid", 1),
            ("Lexus", "RX", "2012-2025", "SUV", "Petrol / Hybrid", 0),
            ("Peugeot", "3008", "2017-2025", "SUV", "Petrol / Diesel", 0),
            ("Mitsubishi", "Pajero", "2012-2021", "SUV", "Diesel", 0),
        ]
        conn.executemany(
            """
            INSERT OR IGNORE INTO car_catalog (make, model, year_range, body_type, fuel_type, popular)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            car_catalog,
        )

        engineer_count = conn.execute(
            "SELECT COUNT(*) AS total FROM users WHERE role = 'engineer'"
        ).fetchone()["total"]

        if engineer_count == 0:
            seed_engineers = [
                (
                    "David Mensah",
                    "david@autoengineer.com",
                    "+233244100001",
                    generate_password_hash("engineer123"),
                    "engineer",
                    "Nigeria",
                    None,
                    "Engine Diagnostics",
                    "7 years",
                    "Specialist in engine tuning, diagnostics, fuel systems, and preventive maintenance.",
                ),
                (
                    "Kofi Boadu",
                    "kofi@autoengineer.com",
                    "+233244100002",
                    generate_password_hash("engineer123"),
                    "engineer",
                    "Nigeria",
                    None,
                    "Electrical Systems",
                    "5 years",
                    "Skilled in electrical fault tracing, battery systems, and modern vehicle electronics.",
                ),
                (
                    "Adwoa Cudjoe",
                    "adwoa@autoengineer.com",
                    "+233244100003",
                    generate_password_hash("engineer123"),
                    "engineer",
                    "Nigeria",
                    None,
                    "Body Repair",
                    "6 years",
                    "Focuses on collision repair, body panel restoration, and paintwork finishes.",
                ),
            ]
            conn.executemany(
                """
                INSERT INTO users (name, email, phone, password_hash, role, location, car_model, specialization, experience, bio)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                seed_engineers,
            )

            conn.execute("UPDATE users SET location = 'Nigeria' WHERE role = 'engineer'")

        if added_verification_column:
            conn.execute("UPDATE users SET verified = 1 WHERE role = 'engineer'")

        users_without_codes = conn.execute(
            "SELECT id FROM users WHERE referral_code IS NULL"
        ).fetchall()
        for existing_user in users_without_codes:
            referral_code = secrets.token_hex(4).upper()
            while conn.execute(
                "SELECT id FROM users WHERE referral_code = ?", (referral_code,)
            ).fetchone():
                referral_code = secrets.token_hex(4).upper()
            conn.execute(
                "UPDATE users SET referral_code = ? WHERE id = ?",
                (referral_code, existing_user["id"]),
            )

        conn.commit()


def ensure_wallet(conn, user_id):
    conn.execute("INSERT OR IGNORE INTO wallets (user_id) VALUES (?)", (user_id,))


def current_user():
    user_id = session.get("user_id")
    if not user_id:
        return None
        

    with get_db() as conn:
        return conn.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
        
# =========================
# AI CUSTOMER CARE HELPERS
# =========================


def detect_emergency(message):
    """
    Detect potentially dangerous vehicle situations.
    This is only a safety filter, not a mechanical diagnosis.
    """
    text = message.lower()

    emergency_keywords = [
        "brake failure",
        "brakes not working",
        "brake not working",
        "no brakes",
        "brakes failed",
        "fire",
        "car is on fire",
        "engine is on fire",
        "smoke coming from engine",
        "heavy smoke",
        "fuel leak",
        "petrol leak",
        "fuel is leaking",
        "petrol is leaking",
        "gasoline leak",
        "crash",
        "accident",
        "collision",
        "stuck on the road",
        "stranded",
        "overheating badly",
        "engine overheating",
        "temperature is red",
        "coolant boiling",
        "wheel came off",
        "tyre burst on highway"
    ]

    matched = [
        keyword for keyword in emergency_keywords
        if keyword in text
    ]

    return len(matched) > 0, matched

def detect_service_category(message):
    """
    Gives the AI a simple starting category for the customer's problem.
    """
    text = message.lower()

    categories = {
        "Brake": [
            "brake",
            "brakes",
            "brake pad",
            "brake disc"
        ],
        "Engine": [
            "engine",
            "piston",
            "oil consumption",
            "engine noise",
            "knocking"
        ],
        "Electrical": [
            "alternator",
            "starter",
            "light",
            "headlight",
            "wiring",
            "electrical",
            "no power"
        ],
        "AC": [
            "ac",
            "air conditioner",
            "air conditioning",
            "cold air",
            "not cooling"
        ],
        "Tyres": [
            "tyre",
            "tire",
            "puncture",
            "flat tyre",
            "flat tire"
        ],
        "Suspension": [
            "shock absorber",
            "shock",
            "suspension",
            "linkage",
            "bushing"
        ],
        "Transmission": [
            "gear",
            "transmission",
            "automatic transmission",
            "gearbox",
            "gear box"
        ],
        "Diagnostics": [
            "check engine",
            "diagnostic",
            "scanner",
            "fault code",
            "error code"
        ],
        "Battery": [
            "battery dead",
            "dead battery",
            "battery weak",
            "battery low"
        ]
    }

    for category, keywords in categories.items():
        for keyword in keywords:
            if keyword in text:
                return category

    return "Other"


# =========================
# AI CUSTOMER CARE PROMPT
# =========================

AI_CUSTOMER_CARE_SYSTEM_PROMPT = """
You are AutoEngineer's official AI Customer Care Assistant.

AutoEngineer is a platform that connects vehicle owners with automobile
engineers and service professionals.

Your job is to help customers:

1. Understand their vehicle-service problem.
2. Identify the likely service category.
3. Explain what information or evidence an engineer may need.
4. Help them create a service request.
5. Explain how AutoEngineer works.
6. Explain quotes, payments, engineers, reviews and disputes.
7. Encourage customers to use verified engineers on the platform.
8. Suggest human engineer assistance when appropriate.

IMPORTANT SAFETY RULES:

- You are NOT a replacement for a qualified automobile engineer.
- Never claim that you have physically inspected a vehicle.
- Never guarantee a mechanical diagnosis from text alone.
- Do not invent prices, engineers, booking status, payment status,
  verification status or account information.
- If a customer describes a dangerous situation, prioritize safety.
- For fire, fuel leaks, brake failure, serious accidents, dangerous
  overheating or another immediate hazard, tell the customer to stop
  driving if safe to do so and seek emergency/professional assistance.
- Do not encourage a customer to continue driving a dangerous vehicle.
- Never request passwords, card PINs, OTPs, Paystack secret keys,
  bank passwords or other sensitive credentials.
- Keep answers concise, friendly and easy to understand.
- Use Nigerian English where appropriate.
- Do not overwhelm the customer with technical jargon.

When appropriate, guide the customer toward:

"Find Engineer → Chat → Get Quote → Approve → Service → Pay → Review"

If the customer needs an engineer, recommend using AutoEngineer's
service-request process rather than pretending to book an engineer
yourself.

You can ask useful follow-up questions such as:

- What vehicle brand and model is it?
- What year is the vehicle?
- What exactly happened?
- When did the problem start?
- Is the vehicle still driveable?
- Are there warning lights on the dashboard?
- Can you upload a picture or video?

Never pretend to have access to information that was not provided.
"""


# =========================
# GENERATE AI RESPONSE
# =========================

def generate_ai_customer_care(user_message, history=None, category="Other"):
    """
    Generate a safe AI Customer Care response.
    """

    if not openai_client:
        return {
            "success": False,
            "message": (
                "AI Customer Care is temporarily unavailable. "
                "Please try again later or contact an engineer through AutoEngineer."
            )
        }

    history = history or []

    messages = []

    for item in history[-10:]:
        role = item.get("role")

        if role not in ("user", "assistant"):
            continue

        body = str(item.get("body", "")).strip()

        if not body:
            continue

        messages.append({
            "role": role,
            "content": body[:2000]
        })

    messages.append({
        "role": "user",
        "content": (
            f"Detected service category: {category}\n\n"
            f"Customer message:\n{user_message}"
        )
    })

    try:
        response = openai_client.responses.create(
            model=OPENAI_MODEL,
            instructions=AI_CUSTOMER_CARE_SYSTEM_PROMPT,
            input=messages,
            max_output_tokens=500
        )

        answer = (response.output_text or "").strip()

        if not answer:
            answer = (
                "I'm sorry, I couldn't generate a response right now. "
                "Please try again."
            )

        return {
            "success": True,
            "message": answer
        }

    except Exception:
        app.logger.exception("AI Customer Care request failed")

        return {
            "success": False,
            "message": (
                "I'm having trouble connecting to AutoEngineer's AI Customer Care "
                "right now. Please try again shortly."
            )
        }


# =========================
# AI CHAT HISTORY
# =========================

def get_ai_chat_history(conn, session_id, user_id=None, limit=10):
    """
    Get recent AI Customer Care messages.
    """

    if user_id:
        rows = conn.execute(
            """
            SELECT role, body
            FROM ai_chat_messages
            WHERE session_id = ?
            AND (user_id = ? OR user_id IS NULL)
            ORDER BY id DESC
            LIMIT ?
            """,
            (session_id, user_id, limit)
        ).fetchall()
    else:
        rows = conn.execute(
            """
            SELECT role, body
            FROM ai_chat_messages
            WHERE session_id = ?
            ORDER BY id DESC
            LIMIT ?
            """,
            (session_id, limit)
        ).fetchall()

    return [
        {
            "role": row["role"],
            "body": row["body"]
        }
        for row in reversed(rows)
    ]
    
def login_required(view):
    @wraps(view)
    def wrapped_view(*args, **kwargs):
        if not current_user():
            return redirect(url_for("login"))
        return view(*args, **kwargs)

    return wrapped_view


def admin_required(view):
    @wraps(view)
    def wrapped_view(*args, **kwargs):
        user = current_user()
        admin_email = os.environ.get("ADMIN_EMAIL", "").strip().lower()
        if not user or not admin_email or user["email"].lower() != admin_email:
            abort(403)
        return view(*args, **kwargs)

    return wrapped_view


def role_required(role):
    def decorator(view):
        @wraps(view)
        def wrapped_view(*args, **kwargs):
            user = current_user()
            if not user or user["role"] != role:
                return redirect(url_for("login"))
            return view(*args, **kwargs)

        return wrapped_view

    return decorator


def ensure_trust_check(conn, user_id):
    conn.execute("INSERT OR IGNORE INTO trust_checks (user_id) VALUES (?)", (user_id,))


def request_access(conn, request_id, user_id):
    return conn.execute(
        "SELECT * FROM service_requests WHERE id = ? AND (customer_id = ? OR engineer_id = ?)",
        (request_id, user_id, user_id),
    ).fetchone()


def paystack_request(endpoint, method="GET", payload=None):
    if not PAYSTACK_SECRET_KEY:
        raise RuntimeError("PAYSTACK_SECRET_KEY is not configured")

    if not PAYSTACK_SECRET_KEY.startswith(("sk_test_", "sk_live_")):
        raise RuntimeError("PAYSTACK_SECRET_KEY format is invalid")

    body = None

    headers = {
        "Authorization": f"Bearer {PAYSTACK_SECRET_KEY}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    if payload is not None:
        body = json.dumps(payload).encode("utf-8")

    request_object = UrlRequest(
        f"{PAYSTACK_BASE_URL}{endpoint}",
        data=body,
        headers=headers,
        method=method,
    )

    try:
        with urlopen(request_object, timeout=20) as response:
            response_body = response.read().decode("utf-8")
            return json.loads(response_body)

    except HTTPError as error:
        error_body = error.read().decode("utf-8", errors="replace")
        app.logger.error(
            "Paystack HTTP error %s: %s",
            error.code,
            error_body
        )
        raise RuntimeError(
            f"Paystack returned HTTP {error.code}: {error_body}"
        ) from error

    except URLError as error:
        app.logger.error(
            "Paystack connection error: %s",
            error.reason
        )
        raise RuntimeError(
            f"Could not connect to Paystack: {error.reason}"
        ) from error

    except (ValueError, json.JSONDecodeError) as error:
        app.logger.error(
            "Invalid Paystack response: %s",
            error
        )
        raise RuntimeError(
            "Paystack returned an invalid response."
        ) from error

def send_phone_otp(phone_number, otp):
    if not TWILIO_ACCOUNT_SID or not TWILIO_AUTH_TOKEN or not TWILIO_FROM_NUMBER:
        return False
    endpoint = f"https://api.twilio.com/2010-04-01/Accounts/{TWILIO_ACCOUNT_SID}/Messages.json"
    body = urlencode({
        "To": phone_number,
        "From": TWILIO_FROM_NUMBER,
        "Body": f"Your AutoEngineer verification code is {otp}. It expires in 10 minutes.",
    }).encode("utf-8")
    credentials = f"{TWILIO_ACCOUNT_SID}:{TWILIO_AUTH_TOKEN}".encode("utf-8")
    headers = {
        "Authorization": "Basic " + base64.b64encode(credentials).decode("ascii"),
        "Content-Type": "application/x-www-form-urlencoded",
    }
    try:
        with urlopen(UrlRequest(endpoint, data=body, headers=headers, method="POST"), timeout=20) as response:
            return 200 <= response.status < 300
    except (HTTPError, URLError, ValueError):
        return False


@app.route("/")
def home():
    return render_template("index.html", current_user=current_user())


# =========================
# AI CUSTOMER CARE API
# =========================

@app.route("/api/ai-customer-care", methods=["POST"])
def ai_customer_care():
    """
    Public AI Customer Care endpoint.

    Customers can use this without logging in.
    Logged-in users get their conversation associated with their account.
    """

    data = request.get_json(silent=True) or {}

    user_message = str(data.get("message", "")).strip()

    if not user_message:
        return {
            "success": False,
            "message": "Please type a message."
        }, 400

    # Prevent extremely large requests
    if len(user_message) > 2000:
        return {
            "success": False,
            "message": "Please keep your message below 2,000 characters."
        }, 400

    # Basic session identification
    if "ai_chat_session_id" not in session:
        session["ai_chat_session_id"] = secrets.token_urlsafe(24)

    session_id = session["ai_chat_session_id"]

    user = current_user()

    user_id = user["id"] if user else None

    # ---------------------------------
    # BASIC RATE LIMIT
    # ---------------------------------

    now = datetime.now(timezone.utc)

    last_ai_request = session.get("last_ai_request")

    if last_ai_request:
        try:
            last_time = datetime.fromisoformat(last_ai_request)

            seconds_since_last = (
                now - last_time
            ).total_seconds()

            if seconds_since_last < 2:
                return {
                    "success": False,
                    "message": "Please wait a moment before sending another message."
                }, 429

        except (ValueError, TypeError):
            pass

    session["last_ai_request"] = now.isoformat()

    # ---------------------------------
    # DETECT EMERGENCY
    # ---------------------------------

    emergency, matched_keywords = detect_emergency(user_message)

    # ---------------------------------
    # DETECT SERVICE CATEGORY
    # ---------------------------------

    category = detect_service_category(user_message)

    with get_db() as conn:

        # ---------------------------------
        # LOAD PREVIOUS CONVERSATION
        # ---------------------------------

        history = get_ai_chat_history(
            conn,
            session_id,
            user_id=user_id,
            limit=10
        )

        # ---------------------------------
        # SAVE CUSTOMER MESSAGE
        # ---------------------------------

        conn.execute(
            """
            INSERT INTO ai_chat_messages
            (user_id, session_id, role, body)
            VALUES (?, ?, ?, ?)
            """,
            (
                user_id,
                session_id,
                "user",
                user_message
            )
        )

        # ---------------------------------
        # EMERGENCY RESPONSE
        # ---------------------------------

        if emergency:

            ai_message = (
                "⚠️ This may be a safety-critical vehicle problem. "
                "If you are currently driving, stop in a safe place if you "
                "can do so safely. Do not continue driving a vehicle with "
                "brake failure, fire, a serious fuel leak or dangerous "
                "overheating. Please contact a qualified engineer or "
                "emergency assistance immediately.\n\n"
                "AutoEngineer can help you request professional assistance."
            )

            handoff = True

        else:

            # ---------------------------------
            # GENERATE AI RESPONSE
            # ---------------------------------

            result = generate_ai_customer_care(
                user_message=user_message,
                history=history,
                category=category
            )

            ai_message = result["message"]

            handoff = False

            # ---------------------------------
            # HUMAN HANDOFF DETECTION
            # ---------------------------------

            handoff_phrases = [
                "engineer",
                "mechanic",
                "inspect",
                "inspection",
                "physical inspection",
                "come and check",
                "need help",
                "book an engineer",
                "request an engineer"
            ]

            lower_message = user_message.lower()

            if any(
                phrase in lower_message
                for phrase in handoff_phrases
            ):
                handoff = True

        # ---------------------------------
        # SAVE AI RESPONSE
        # ---------------------------------

        conn.execute(
            """
            INSERT INTO ai_chat_messages
            (user_id, session_id, role, body)
            VALUES (?, ?, ?, ?)
            """,
            (
                user_id,
                session_id,
                "assistant",
                ai_message
            )
        )

        conn.commit()

    return {
        "success": True,
        "message": ai_message,
        "category": category,
        "emergency": emergency,
        "handoff": handoff
    }


@app.route("/api/ai-customer-care/clear", methods=["POST"])
def clear_ai_customer_care():
    """
    Clear the current AI Customer Care conversation.
    """

    session_id = session.get("ai_chat_session_id")

    if not session_id:
        return {
            "success": True
        }

    user = current_user()

    user_id = user["id"] if user else None

    with get_db() as conn:

        if user_id:
            conn.execute(
                """
                DELETE FROM ai_chat_messages
                WHERE session_id = ?
                AND (user_id = ? OR user_id IS NULL)
                """,
                (
                    session_id,
                    user_id
                )
            )
        else:
            conn.execute(
                """
                DELETE FROM ai_chat_messages
                WHERE session_id = ?
                """,
                (session_id,)
            )

        conn.commit()

    return {
        "success": True,
        "message": "AI Customer Care chat cleared."
    }
@app.route("/home")
def home_alias():
    return redirect(url_for("home"))


@app.route("/health")
def health():
    return {"status": "ok", "service": "autoengineer"}


@app.errorhandler(404)
def not_found(error):
    return render_template("404.html", current_user=current_user()), 404


@app.route("/about")
def about():
    return render_template("about.html", current_user=current_user())


@app.route("/login", methods=["GET", "POST"])
def login():
    selected_role = request.args.get("role", request.form.get("role", "customer"))
    if selected_role not in {"customer", "engineer"}:
        selected_role = "customer"
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")

        if not email or not password:
            flash("Email and password are required.")
            return render_template("login.html", current_user=current_user(), selected_role=selected_role)

        with get_db() as conn:
            user = conn.execute("SELECT * FROM users WHERE email = ? AND role = ?", (email, selected_role)).fetchone()

        if user and check_password_hash(user["password_hash"], password):
            session["user_id"] = user["id"]
            session["user_type"] = user["role"]
            session.permanent = True
            if user["role"] == "engineer":
                return redirect(url_for("engineer_dashboard"))
            return redirect(url_for("customer_dashboard"))

        flash("Invalid email or password.")

    return render_template("login.html", current_user=current_user(), selected_role=selected_role)


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))


@app.route("/customer-register", methods=["GET", "POST"])
def customer_register():
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip().lower()
        phone = request.form.get("phone", "").strip()
        password = request.form.get("password", "")
        car_model = request.form.get("car_model", "").strip()
        referral_code = request.form.get("referral_code", "").strip().upper()
        location = "Nigeria"

        if not all([name, email, phone, password, car_model, location]):
            flash("Please fill in all customer details.")
            return render_template("customer_register.html", current_user=current_user())

        with get_db() as conn:
            existing = conn.execute("SELECT id FROM users WHERE email = ?", (email,)).fetchone()
            if existing:
                flash("An account with this email already exists.")
                return render_template("customer_register.html", current_user=current_user())

            referrer = None
            if referral_code:
                referrer = conn.execute(
                    "SELECT id FROM users WHERE referral_code = ?", (referral_code,)
                ).fetchone()
                if not referrer:
                    flash("That referral code is not valid.")
                    return render_template("customer_register.html", current_user=current_user())

            new_referral_code = secrets.token_hex(4).upper()
            while conn.execute(
                "SELECT id FROM users WHERE referral_code = ?", (new_referral_code,)
            ).fetchone():
                new_referral_code = secrets.token_hex(4).upper()

            conn.execute(
                """
                INSERT INTO users (name, email, phone, password_hash, role, location, car_model, referral_code, referred_by)
                VALUES (?, ?, ?, ?, 'customer', ?, ?, ?, ?)
                RETURNING id
                """,
                (name, email, phone, generate_password_hash(password), location, car_model,
                 new_referral_code, referrer["id"] if referrer else None),
            )
            new_user_id = conn.execute("SELECT id FROM users WHERE email = ?", (email,)).fetchone()["id"]
            ensure_wallet(conn, new_user_id)
            if referrer:
                ensure_wallet(conn, referrer["id"])
                conn.execute(
                    "UPDATE wallets SET balance = balance + 200 WHERE user_id = ?",
                    (referrer["id"],),
                )
            conn.commit()

        flash("Customer account created successfully. Please log in.")
        return redirect(url_for("login"))

    return render_template("customer_register.html", current_user=current_user())


@app.route("/engineer-register", methods=["GET", "POST"])
def engineer_register():
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip().lower()
        phone = request.form.get("phone", "").strip()
        password = request.form.get("password", "")
        specialization = request.form.get("specialization", "").strip()
        location = request.form.get("location", "").strip()
        experience = request.form.get("experience", "").strip()
        bio = request.form.get("bio", "").strip()

        if not all([name, email, phone, password, specialization, location, experience]):
            flash("Please complete all engineer registration fields.")
            return render_template("enginer_register.html", current_user=current_user())

        with get_db() as conn:
            existing = conn.execute("SELECT id FROM users WHERE email = ?", (email,)).fetchone()
            if existing:
                flash("An engineer account with this email already exists.")
                return render_template("enginer_register.html", current_user=current_user())

            referral_code = secrets.token_hex(4).upper()
            while conn.execute(
                "SELECT id FROM users WHERE referral_code = ?", (referral_code,)
            ).fetchone():
                referral_code = secrets.token_hex(4).upper()

            conn.execute(
                """
                INSERT INTO users (name, email, phone, password_hash, role, location, specialization, experience, bio, referral_code)
                VALUES (?, ?, ?, ?, 'engineer', ?, ?, ?, ?, ?)
                """,
                (name, email, phone, generate_password_hash(password), location, specialization, experience, bio, referral_code),
            )
            conn.commit()

        flash("Engineer account created successfully. Please log in.")
        return redirect(url_for("login"))

    return render_template("enginer_register.html", current_user=current_user())


@app.route("/customer-dashboard")
def customer_dashboard():
    user = current_user()
    if not user or user["role"] != "customer":
        return redirect(url_for("login"))

    with get_db() as conn:
        open_requests = conn.execute(
            "SELECT sr.*, u.name AS engineer_name FROM service_requests sr LEFT JOIN users u ON u.id = sr.engineer_id WHERE sr.customer_id = ? ORDER BY sr.created_at DESC",
            (user["id"],),
        ).fetchall()

        total_requests = len(open_requests)
        pending_requests = sum(1 for request in open_requests if request["status"] == "pending")
        completed_requests = sum(1 for request in open_requests if request["status"] == "completed")

    return render_template(
        "customer_dashboard.html",
        current_user=user,
        user=user,
        requests=open_requests,
        total_requests=total_requests,
        pending_requests=pending_requests,
        completed_requests=completed_requests,
    )


@app.route("/engineer-dashboard")
def engineer_dashboard():
    user = current_user()
    if not user or user["role"] != "engineer":
        return redirect(url_for("login"))

    with get_db() as conn:
        jobs = conn.execute(
            """
            SELECT sr.*, c.name AS customer_name, c.phone AS customer_phone
            FROM service_requests sr
            JOIN users c ON c.id = sr.customer_id
            WHERE sr.engineer_id = ?
            ORDER BY sr.created_at DESC
            """,
            (user["id"],),
        ).fetchall()

        total_jobs = len(jobs)
        pending_jobs = sum(1 for job in jobs if job["status"] == "pending")
        completed_jobs = sum(1 for job in jobs if job["status"] == "completed")

    return render_template(
        "engineer_dashboard.html",
        current_user=user,
        user=user,
        jobs=jobs,
        total_jobs=total_jobs,
        pending_jobs=pending_jobs,
        completed_jobs=completed_jobs,
    )


@app.route("/update-request-status/<int:request_id>", methods=["POST"])
def update_request_status(request_id):
    user = current_user()
    if not user or user["role"] != "engineer":
        return redirect(url_for("login"))

    status = request.form.get("status", "pending")
    if status not in {"pending", "en_route", "in_progress", "completed"}:
        status = "pending"

    with get_db() as conn:
        conn.execute(
            "UPDATE service_requests SET status = ? WHERE id = ? AND engineer_id = ?",
            (status, request_id, user["id"]),
        )
        conn.commit()

    flash("Service request status updated.")
    return redirect(url_for("engineer_dashboard"))


@app.route("/api/service-requests/<int:request_id>/location", methods=["GET", "POST"])
@login_required
def service_request_location(request_id):
    user = current_user()
    with get_db() as conn:
        service_request = conn.execute(
            "SELECT * FROM service_requests WHERE id = ? AND (customer_id = ? OR engineer_id = ?)",
            (request_id, user["id"], user["id"]),
        ).fetchone()
        if not service_request:
            abort(404)

        if request.method == "POST":
            if service_request["engineer_id"] != user["id"]:
                abort(403)
            coordinates = request.get_json(silent=True) or {}
            latitude = coordinates.get("latitude")
            longitude = coordinates.get("longitude")
            if not isinstance(latitude, (int, float)) or not isinstance(longitude, (int, float)):
                return {"error": "Valid coordinates are required."}, 400
            if not -90 <= latitude <= 90 or not -180 <= longitude <= 180:
                return {"error": "Coordinates are outside valid bounds."}, 400
            conn.execute(
                "UPDATE service_requests SET engineer_lat = ?, engineer_lng = ?, location_updated_at = CURRENT_TIMESTAMP WHERE id = ?",
                (latitude, longitude, request_id),
            )
            conn.commit()
            return {"ok": True, "latitude": latitude, "longitude": longitude}

    return {
        "request_id": service_request["id"],
        "status": service_request["status"],
        "customer_lat": service_request["customer_lat"],
        "customer_lng": service_request["customer_lng"],
        "engineer_lat": service_request["engineer_lat"],
        "engineer_lng": service_request["engineer_lng"],
        "location_updated_at": service_request["location_updated_at"],
    }


@app.route("/find-engineers")
def find_engineers():
    with get_db() as conn:
        engineers = conn.execute(
            "SELECT * FROM users WHERE role = 'engineer' AND verified = 1 ORDER BY name ASC"
        ).fetchall()

    return render_template("find_engineers.html", current_user=current_user(), engineers=engineers)


@app.route("/cars")
def cars():
    search = request.args.get("q", "").strip()
    make = request.args.get("make", "").strip()
    query = "SELECT * FROM car_catalog WHERE 1 = 1"
    parameters = []
    if search:
        query += " AND (make LIKE ? OR model LIKE ?)"
        parameters.extend([f"%{search}%", f"%{search}%"])
    if make:
        query += " AND make = ?"
        parameters.append(make)
    query += " ORDER BY popular DESC, make ASC, model ASC"
    with get_db() as conn:
        catalog = conn.execute(query, parameters).fetchall()
        makes = conn.execute("SELECT DISTINCT make FROM car_catalog ORDER BY make ASC").fetchall()
    return render_template("cars.html", current_user=current_user(), catalog=catalog, makes=makes, search=search, selected_make=make)


@app.route("/engineer-profile/<int:engineer_id>")
def engineer_profile(engineer_id):
    with get_db() as conn:
        engineer = conn.execute(
            "SELECT * FROM users WHERE id = ? AND role = 'engineer' AND verified = 1",
            (engineer_id,),
        ).fetchone()

    if not engineer:
        return redirect(url_for("find_engineers"))

    return render_template("engineer_profile.html", current_user=current_user(), engineer=engineer)


@app.route("/request-service", methods=["GET", "POST"])
def request_service():
    user = current_user()
    if not user or user["role"] != "customer":
        return redirect(url_for("login"))

    with get_db() as conn:
        engineers = conn.execute(
            "SELECT * FROM users WHERE role = 'engineer' AND verified = 1 ORDER BY name ASC"
        ).fetchall()

    if request.method == "POST":
        engineer_id = request.form.get("engineer_id")
        service_type = request.form.get("service_type", "").strip()
        problem = request.form.get("problem", "").strip()
        location = request.form.get("location", "").strip()
        customer_lat = request.form.get("customer_lat", type=float)
        customer_lng = request.form.get("customer_lng", type=float)

        if not all([engineer_id, service_type, problem, location]):
            flash("Please complete all service request details.")
            return render_template("request_service.html", current_user=user, engineers=engineers)

        with get_db() as conn:
            selected_engineer = conn.execute(
                "SELECT id FROM users WHERE id = ? AND role = 'engineer' AND verified = 1",
                (engineer_id,),
            ).fetchone()
            if not selected_engineer:
                flash("Please select a verified engineer.")
                return render_template("request_service.html", current_user=user, engineers=engineers)
            conn.execute(
                """
                INSERT INTO service_requests (customer_id, engineer_id, service_type, problem, location, customer_lat, customer_lng, status)
                VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')
                """,
                (user["id"], engineer_id, service_type, problem, location, customer_lat, customer_lng),
            )
            conn.commit()

        flash("Your service request has been sent successfully.")
        return redirect(url_for("customer_dashboard"))

    return render_template("request_service.html", current_user=user, engineers=engineers)


@app.route("/admin/engineers")
@admin_required
def admin_engineers():
    with get_db() as conn:
        engineers = conn.execute(
            "SELECT * FROM users WHERE role = 'engineer' ORDER BY verified ASC, name ASC"
        ).fetchall()
    return render_template("admin_engineers.html", current_user=current_user(), engineers=engineers)


@app.route("/admin/engineers/<int:engineer_id>/verify", methods=["POST"])
@admin_required
def verify_engineer(engineer_id):
    with get_db() as conn:
        conn.execute(
            "UPDATE users SET verified = 1 WHERE id = ? AND role = 'engineer'",
            (engineer_id,),
        )
        conn.commit()
    flash("Engineer verification updated.")
    return redirect(url_for("admin_engineers"))


@app.route("/workspace")
@login_required
def workspace():
    user = current_user()
    with get_db() as conn:
        ensure_trust_check(conn, user["id"])
        trust = conn.execute("SELECT * FROM trust_checks WHERE user_id = ?", (user["id"],)).fetchone()
        if user["role"] == "engineer":
            jobs = conn.execute(
                "SELECT sr.*, u.name AS customer_name FROM service_requests sr JOIN users u ON u.id = sr.customer_id WHERE sr.engineer_id = ? ORDER BY sr.created_at DESC",
                (user["id"],),
            ).fetchall()
            quotes = conn.execute("SELECT * FROM quotes WHERE engineer_id = ? ORDER BY created_at DESC", (user["id"],)).fetchall()
            payments = conn.execute("SELECT * FROM payments WHERE engineer_id = ? ORDER BY created_at DESC", (user["id"],)).fetchall()
            reviews = conn.execute("SELECT * FROM reviews WHERE reviewee_id = ? ORDER BY created_at DESC", (user["id"],)).fetchall()
            return render_template("workspace.html", current_user=user, trust=trust, jobs=jobs, quotes=quotes, payments=payments, reviews=reviews)
        bookings = conn.execute(
            "SELECT sr.*, u.name AS engineer_name FROM service_requests sr LEFT JOIN users u ON u.id = sr.engineer_id WHERE sr.customer_id = ? ORDER BY sr.created_at DESC",
            (user["id"],),
        ).fetchall()
        reviews = conn.execute("SELECT * FROM reviews WHERE reviewer_id = ? ORDER BY created_at DESC", (user["id"],)).fetchall()
        refunds = conn.execute("SELECT * FROM refund_requests WHERE customer_id = ? ORDER BY created_at DESC", (user["id"],)).fetchall()
        messages = conn.execute("SELECT * FROM messages WHERE sender_id = ? OR recipient_id = ? ORDER BY created_at DESC", (user["id"], user["id"])).fetchall()
        return render_template("workspace.html", current_user=user, trust=trust, bookings=bookings, reviews=reviews, refunds=refunds, messages=messages)


@app.route("/quotes/<int:request_id>", methods=["POST"])
@role_required("engineer")
def create_quote(request_id):
    user = current_user()
    amount = request.form.get("amount", type=int)
    notes = request.form.get("notes", "").strip()
    with get_db() as conn:
        service_request = conn.execute(
            "SELECT * FROM service_requests WHERE id = ? AND engineer_id = ?", (request_id, user["id"])
        ).fetchone()
        if not service_request or not amount or amount <= 0 or not notes:
            flash("A valid amount and quote note are required.")
        else:
            conn.execute(
                "INSERT INTO quotes (request_id, engineer_id, customer_id, amount, notes) VALUES (?, ?, ?, ?, ?)",
                (request_id, user["id"], service_request["customer_id"], amount, notes),
            )
            conn.commit()
            flash("Quote sent to the customer.")
    return redirect(url_for("workspace"))


@app.route("/reviews/<int:request_id>", methods=["POST"])
@role_required("customer")
def create_review(request_id):
    user = current_user()
    rating = request.form.get("rating", type=int)
    comment = request.form.get("comment", "").strip()
    with get_db() as conn:
        service_request = conn.execute(
            "SELECT * FROM service_requests WHERE id = ? AND customer_id = ? AND status = 'completed'",
            (request_id, user["id"]),
        ).fetchone()
        existing = conn.execute("SELECT id FROM reviews WHERE request_id = ? AND reviewer_id = ?", (request_id, user["id"])).fetchone()
        if not service_request or existing or rating not in {1, 2, 3, 4, 5} or not comment:
            flash("Reviews require a completed booking, a rating, and a comment.")
        else:
            conn.execute("INSERT INTO reviews (request_id, reviewer_id, reviewee_id, rating, comment) VALUES (?, ?, ?, ?, ?)", (request_id, user["id"], service_request["engineer_id"], rating, comment))
            conn.commit()
            flash("Review submitted.")
    return redirect(url_for("workspace"))


@app.route("/refunds/<int:request_id>", methods=["POST"])
@role_required("customer")
def create_refund(request_id):
    user = current_user()
    amount = request.form.get("amount", type=int)
    reason = request.form.get("reason", "").strip()
    with get_db() as conn:
        service_request = conn.execute("SELECT id FROM service_requests WHERE id = ? AND customer_id = ?", (request_id, user["id"])).fetchone()
        if not service_request or not amount or amount <= 0 or not reason:
            flash("Refund amount and reason are required.")
        else:
            conn.execute("INSERT INTO refund_requests (request_id, customer_id, amount, reason) VALUES (?, ?, ?, ?)", (request_id, user["id"], amount, reason))
            conn.commit()
            flash("Refund request sent for review.")
    return redirect(url_for("workspace"))


@app.route("/messages/<int:request_id>", methods=["POST"])
@login_required
def create_message(request_id):
    user = current_user()
    body = request.form.get("body", "").strip()
    with get_db() as conn:
        service_request = request_access(conn, request_id, user["id"])
        if not service_request or not body:
            flash("Only booking participants can send messages.")
        else:
            recipient_id = service_request["engineer_id"] if service_request["customer_id"] == user["id"] else service_request["customer_id"]
            conn.execute("INSERT INTO messages (request_id, sender_id, recipient_id, body) VALUES (?, ?, ?, ?)", (request_id, user["id"], recipient_id, body))
            conn.commit()
            flash("Message sent securely in the app.")
    return redirect(url_for("workspace"))


@app.route("/payments/initialize/<int:request_id>", methods=["POST"])
@role_required("customer")
def initialize_payment(request_id):
    user = current_user()
    amount = request.form.get("amount", type=int)
    payment_method = request.form.get("payment_method", "online")

    channels = {
        "bank": ["bank_transfer"],
        "card": ["card"],
        "ussd": ["ussd"],
        "online": ["card", "bank_transfer", "ussd"],
    }

    if payment_method not in channels:
        abort(400)

    with get_db() as conn:
        service_request = conn.execute(
            "SELECT * FROM service_requests WHERE id = ? AND customer_id = ?",
            (request_id, user["id"]),
        ).fetchone()

        if not service_request or not amount or amount <= 0:
            flash("Enter a valid payment amount for your booking.")
            return redirect(url_for("workspace"))

        reference = f"AE-{request_id}-{secrets.token_hex(8).upper()}"

        try:
            result = paystack_request(
                "/transaction/initialize",
                method="POST",
                payload={
                    "email": user["email"],
                    "amount": amount * 100,
                    "currency": "NGN",
                    "reference": reference,
                    "channels": channels[payment_method],
                    "callback_url": url_for(
                        "payment_callback",
                        _external=True
                    ),
                    "metadata": {
                        "request_id": request_id,
                        "customer_id": user["id"],
                    },
                },
            )

        except RuntimeError as error:
            app.logger.error(
                "Paystack payment initialization failed: %s",
                error
            )
            flash(
                "Paystack payment initialization failed. "
                "Please try again."
            )
            return redirect(url_for("workspace"))

        if not result.get("status") or not result.get("data", {}).get("authorization_url"):
            flash("Paystack could not initialize this payment.")
            return redirect(url_for("workspace"))

        engineer_id = service_request["engineer_id"]
        commission = round(amount * 0.10)

        conn.execute(
            """
            INSERT INTO payments
            (
                request_id,
                customer_id,
                engineer_id,
                amount,
                commission,
                status,
                reference,
                channel,
                provider
            )
            VALUES (?, ?, ?, ?, ?, 'pending', ?, ?, 'paystack')
            """,
            (
                request_id,
                user["id"],
                engineer_id,
                amount,
                commission,
                reference,
                payment_method,
            ),
        )

        conn.commit()

        return redirect(result["data"]["authorization_url"])


@app.route("/payments/callback")
@login_required
def payment_callback():
    reference = request.args.get("reference", "").strip()
    if not reference:
        flash("Payment reference was not supplied.")
        return redirect(url_for("workspace"))
    try:
        result = paystack_request(f"/transaction/verify/{reference}")
    except (RuntimeError, HTTPError, URLError, ValueError):
        flash("Payment verification could not be completed. Please contact support.")
        return redirect(url_for("workspace"))

    transaction = result.get("data", {})
    paid = result.get("status") and transaction.get("status") == "success"
    user = current_user()
    with get_db() as conn:
        payment = conn.execute(
            "SELECT * FROM payments WHERE reference = ? AND customer_id = ?",
            (reference, user["id"]),
        ).fetchone()
        if not payment:
            abort(404)
        if paid and transaction.get("amount") == payment["amount"] * 100:
            conn.execute(
                "UPDATE payments SET status = 'paid' WHERE id = ? AND status = 'pending'",
                (payment["id"],),
            )
            conn.execute(
                "UPDATE service_requests SET status = 'paid' WHERE id = ? AND customer_id = ?",
                (payment["request_id"], user["id"]),
            )
            conn.commit()
            flash("Payment confirmed successfully through Paystack.")
        else:
            conn.execute("UPDATE payments SET status = 'failed' WHERE id = ?", (payment["id"],))
            conn.commit()
            flash("Paystack did not confirm this payment.")
    return redirect(url_for("workspace"))


@app.route("/payments/webhook", methods=["POST"])
def payment_webhook():
    signature = request.headers.get("x-paystack-signature", "")
    expected_signature = hmac.new(
        PAYSTACK_SECRET_KEY.encode("utf-8"),
        request.get_data(),
        hashlib.sha512,
    ).hexdigest()
    if not PAYSTACK_SECRET_KEY or not hmac.compare_digest(signature, expected_signature):
        abort(401)

    payload = request.get_json(silent=True) or {}
    if payload.get("event") != "charge.success":
        return "ignored", 200
    transaction = payload.get("data", {})
    reference = transaction.get("reference")
    with get_db() as conn:
        payment = conn.execute(
            "SELECT * FROM payments WHERE reference = ?", (reference,)
        ).fetchone()
        if payment and transaction.get("amount") == payment["amount"] * 100:
            conn.execute(
                "UPDATE payments SET status = 'paid' WHERE id = ? AND status = 'pending'",
                (payment["id"],),
            )
            conn.execute(
                "UPDATE service_requests SET status = 'paid' WHERE id = ?",
                (payment["request_id"],),
            )
            conn.commit()
        subscription = conn.execute(
            "SELECT * FROM subscriptions WHERE reference = ?", (reference,)
        ).fetchone()
        if subscription and transaction.get("amount") == subscription["amount"] * 100:
            expires_at = datetime.now(timezone.utc) + timedelta(days=PREMIUM_PLANS[subscription["billing_cycle"]]["days"])
            conn.execute(
                "UPDATE subscriptions SET status = 'active', paid_at = CURRENT_TIMESTAMP, expires_at = ? WHERE id = ? AND status = 'pending'",
                (expires_at.isoformat(), subscription["id"]),
            )
            conn.commit()
    return "ok", 200


@app.route("/subscriptions/initialize", methods=["GET", "POST"])
@role_required("engineer")
def initialize_subscription():
    user = current_user()
    billing_cycle = request.values.get("billing_cycle", "monthly")
    plan = PREMIUM_PLANS.get(billing_cycle)
    if not plan:
        abort(400)

    reference = f"AE-SUB-{user['id']}-{secrets.token_hex(8).upper()}"
    payload = {
        "email": user["email"],
        "amount": plan["amount"] * 100,
        "currency": "NGN",
        "reference": reference,
        "callback_url": url_for("subscription_callback", _external=True),
        "metadata": {
            "type": "premium_subscription",
            "user_id": user["id"],
            "billing_cycle": billing_cycle,
        },
    }
    plan_code = PREMIUM_PAYSTACK_PLAN_CODES.get(billing_cycle)
    if plan_code:
        payload["plan"] = plan_code

    try:
        result = paystack_request("/transaction/initialize", method="POST", payload=payload)
    except RuntimeError as error:
        app.logger.error("Paystack payment initialization failed: %s", error)
        flash("Paystack payment initialization failed. Please try again.")
        return redirect(url_for("workspace"))
        return redirect(url_for("business"))
    authorization_url = result.get("data", {}).get("authorization_url")
    if not result.get("status") or not authorization_url:
        flash("Paystack could not initialize this subscription.")
        return redirect(url_for("business"))

    with get_db() as conn:
        conn.execute(
            "UPDATE subscriptions SET status = 'cancelled' WHERE engineer_id = ? AND status = 'pending'",
            (user["id"],),
        )
        conn.execute(
            """
            INSERT INTO subscriptions (engineer_id, plan, billing_cycle, amount, reference, provider, status)
            VALUES (?, 'premium', ?, ?, ?, 'paystack', 'pending')
            """,
            (user["id"], billing_cycle, plan["amount"], reference),
        )
        conn.commit()
    return redirect(authorization_url)


@app.route("/subscriptions/callback")
@login_required
def subscription_callback():
    reference = request.args.get("reference", "").strip()
    user = current_user()
    if not reference:
        flash("Subscription payment reference was not supplied.")
        return redirect(url_for("business"))
    try:
        result = paystack_request(f"/transaction/verify/{reference}")
    except (RuntimeError, HTTPError, URLError, ValueError):
        flash("Subscription payment verification could not be completed.")
        return redirect(url_for("business"))

    transaction = result.get("data", {})
    with get_db() as conn:
        subscription = conn.execute(
            "SELECT * FROM subscriptions WHERE reference = ? AND engineer_id = ?",
            (reference, user["id"]),
        ).fetchone()
        paid = result.get("status") and transaction.get("status") == "success"
        valid_amount = subscription and transaction.get("amount") == subscription["amount"] * 100
        if not subscription:
            abort(404)
        if paid and valid_amount:
            expires_at = datetime.now(timezone.utc) + timedelta(days=PREMIUM_PLANS[subscription["billing_cycle"]]["days"])
            conn.execute(
                "UPDATE subscriptions SET status = 'active', paid_at = CURRENT_TIMESTAMP, expires_at = ? WHERE id = ? AND status = 'pending'",
                (expires_at.isoformat(), subscription["id"]),
            )
            conn.commit()
            flash(f"Premium {subscription['billing_cycle']} subscription is active.")
        else:
            conn.execute("UPDATE subscriptions SET status = 'failed' WHERE id = ? AND status = 'pending'", (subscription["id"],))
            conn.commit()
            flash("Paystack did not confirm this subscription payment.")
    return redirect(url_for("business"))


@app.route("/disputes/<int:request_id>", methods=["POST"])
@login_required
def create_dispute(request_id):
    user = current_user()
    reason = request.form.get("reason", "").strip()
    with get_db() as conn:
        if not request_access(conn, request_id, user["id"]) or not reason:
            flash("A dispute reason is required.")
        else:
            conn.execute("INSERT INTO disputes (request_id, opened_by, reason) VALUES (?, ?, ?)", (request_id, user["id"], reason))
            conn.commit()
            flash("Dispute opened for admin review.")
    return redirect(url_for("workspace"))


@app.route("/trust/phone", methods=["POST"])
@login_required
def request_phone_verification():
    user = current_user()
    otp = f"{secrets.randbelow(1000000):06d}"
    with get_db() as conn:
        ensure_trust_check(conn, user["id"])
        conn.execute(
            "UPDATE trust_checks SET phone_status = 'otp_pending', otp_hash = ?, otp_expires_at = ?, otp_attempts = 0, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?",
            (generate_password_hash(otp), (datetime.now(timezone.utc) + timedelta(minutes=10)).isoformat(), user["id"]),
        )
        conn.commit()
    if send_phone_otp(user["phone"], otp):
        flash("Phone OTP sent by SMS. It expires in 10 minutes.")
    elif os.environ.get("FLASK_ENV") == "production":
        flash("We could not send your phone OTP. Please contact support or try again later.")
    else:
        flash(f"Phone OTP created for local testing: {otp}. Configure Twilio for SMS delivery.")
    return redirect(url_for("workspace"))


@app.route("/trust/phone/verify", methods=["POST"])
@login_required
def verify_phone():
    user = current_user()
    submitted_otp = request.form.get("otp", "").strip()
    with get_db() as conn:
        ensure_trust_check(conn, user["id"])
        trust = conn.execute("SELECT * FROM trust_checks WHERE user_id = ?", (user["id"],)).fetchone()
        expires_at = trust["otp_expires_at"]
        expired = not expires_at or datetime.fromisoformat(expires_at) < datetime.now(timezone.utc)
        if expired or trust["otp_attempts"] >= 5:
            flash("This OTP has expired. Request a new code.")
        elif not submitted_otp.isdigit() or len(submitted_otp) != 6 or not check_password_hash(trust["otp_hash"], submitted_otp):
            conn.execute("UPDATE trust_checks SET otp_attempts = otp_attempts + 1 WHERE user_id = ?", (user["id"],))
            conn.commit()
            flash("The OTP is incorrect.")
        else:
            conn.execute("UPDATE trust_checks SET phone_status = 'verified', otp_hash = NULL, otp_expires_at = NULL, otp_attempts = 0, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?", (user["id"],))
            conn.commit()
            flash("Phone number verified successfully.")
    return redirect(url_for("workspace"))


@app.route("/trust/identity", methods=["POST"])
@login_required
def submit_identity_verification():
    user = current_user()
    identity_type = request.form.get("identity_type", "").lower()
    identity_number = request.form.get("identity_number", "").strip()
    if identity_type not in {"nin", "bvn"} or not identity_number.isdigit() or len(identity_number) != 11:
        flash("Enter a valid 11-digit NIN or BVN.")
        return redirect(url_for("workspace"))
    with get_db() as conn:
        ensure_trust_check(conn, user["id"])
        conn.execute(
            f"UPDATE trust_checks SET identity_status = 'pending', {identity_type}_status = 'pending', {identity_type}_last4 = ?, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?",
            (identity_number[-4:], user["id"]),
        )
        conn.commit()
    flash(f"{identity_type.upper()} submitted for verification review.")
    return redirect(url_for("workspace"))

@app.route("/admin/control")
@admin_required
def admin_control():
    with get_db() as conn:
        data = {
            "users": conn.execute("SELECT * FROM users ORDER BY created_at DESC").fetchall(),
            "payments": conn.execute("SELECT * FROM payments ORDER BY created_at DESC").fetchall(),
            "refunds": conn.execute("SELECT * FROM refund_requests ORDER BY created_at DESC").fetchall(),
            "disputes": conn.execute("SELECT * FROM disputes ORDER BY created_at DESC").fetchall(),
            "fraud_flags": conn.execute("SELECT * FROM fraud_flags ORDER BY created_at DESC").fetchall(),
        }
    return render_template("admin_control.html", current_user=current_user(), **data)


@app.route("/admin/verifications")
@admin_required
def admin_verifications():
    with get_db() as conn:
        verifications = conn.execute(
            """
            SELECT tc.*, u.name, u.email, u.role
            FROM trust_checks tc
            JOIN users u ON u.id = tc.user_id
                WHERE tc.phone_status = 'otp_pending'
                    OR (tc.nin_status = 'pending' AND tc.nin_last4 IS NOT NULL)
                    OR (tc.bvn_status = 'pending' AND tc.bvn_last4 IS NOT NULL)
            ORDER BY tc.updated_at DESC
            """
        ).fetchall()
    return render_template("admin_verifications.html", current_user=current_user(), verifications=verifications)


@app.route("/admin/verifications/<int:user_id>/<string:verification_type>", methods=["POST"])
@admin_required
def update_verification(user_id, verification_type):
    if verification_type not in {"identity", "phone", "nin", "bvn"}:
        abort(400)
    status = request.form.get("status")
    if status not in {"verified", "rejected"}:
        abort(400)
    with get_db() as conn:
        conn.execute(
            f"UPDATE trust_checks SET {verification_type}_status = ?, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?",
            (status, user_id),
        )
        if verification_type in {"nin", "bvn"}:
            conn.execute(
                "UPDATE trust_checks SET identity_status = ? WHERE user_id = ?",
                (status, user_id),
            )
        conn.commit()
    flash("Verification status updated.")
    return redirect(url_for("admin_verifications"))


@app.route("/admin/control/<string:record_type>/<int:record_id>", methods=["POST"])
@admin_required
def update_admin_record(record_type, record_id):
    allowed = {"refunds": "refund_requests", "disputes": "disputes", "payments": "payments", "fraud_flags": "fraud_flags"}
    statuses = {"refunds": {"approved", "rejected", "paid"}, "disputes": {"open", "investigating", "resolved"}, "payments": {"pending", "paid", "failed"}, "fraud_flags": {"open", "cleared"}}
    table = allowed.get(record_type)
    status = request.form.get("status")
    if not table or status not in statuses[record_type]:
        abort(400)
    with get_db() as conn:
        conn.execute(f"UPDATE {table} SET status = ? WHERE id = ?", (status, record_id))
        conn.commit()
    flash("Admin record updated.")
    return redirect(url_for("admin_control"))


@app.route("/business", methods=["GET", "POST"])
@login_required
def business():
    user = current_user()
    if request.method == "POST":
        action = request.form.get("action")
        with get_db() as conn:
            if action == "subscribe" and user["role"] == "engineer":
                billing_cycle = request.form.get("billing_cycle", "monthly")
                if billing_cycle not in PREMIUM_PLANS:
                    abort(400)
                return redirect(url_for("initialize_subscription", billing_cycle=billing_cycle))
            elif action == "fleet":
                company_name = request.form.get("company_name", "").strip()
                vehicles = request.form.get("vehicles", type=int)
                if not company_name or not vehicles or vehicles < 1:
                    flash("Company name and vehicle count are required.")
                else:
                    conn.execute("INSERT INTO fleet_accounts (owner_id, company_name, vehicles) VALUES (?, ?, ?)", (user["id"], company_name, vehicles))
                    conn.commit()
                    flash("Fleet service inquiry submitted.")
        return redirect(url_for("business"))
    with get_db() as conn:
        conn.execute(
            "UPDATE subscriptions SET status = 'expired' WHERE engineer_id = ? AND status = 'active' AND expires_at IS NOT NULL AND expires_at < CURRENT_TIMESTAMP",
            (user["id"],),
        )
        subscriptions = conn.execute("SELECT * FROM subscriptions WHERE engineer_id = ? ORDER BY created_at DESC", (user["id"],)).fetchall() if user["role"] == "engineer" else []
        fleets = conn.execute("SELECT * FROM fleet_accounts WHERE owner_id = ? ORDER BY created_at DESC", (user["id"],)).fetchall()
        commission = conn.execute("SELECT COALESCE(SUM(commission), 0) AS total FROM payments").fetchone()["total"]
    return render_template("business.html", current_user=user, subscriptions=subscriptions, fleets=fleets, commission=commission, premium_plans=PREMIUM_PLANS)


@app.route("/profile")
def profile():
    user = current_user()
    if not user:
        return redirect(url_for("login"))
    return render_template("profile.html", current_user=user, user=user)


@app.route("/bonuses", methods=["GET", "POST"])
def bonuses():
    user = current_user()
    if not user:
        return redirect(url_for("login"))

    if request.method == "POST":
        amount_text = request.form.get("amount", "").strip()
        account_name = request.form.get("account_name", "").strip()
        account_number = request.form.get("account_number", "").strip()
        bank_name = request.form.get("bank_name", "").strip()
        try:
            amount = int(amount_text)
        except ValueError:
            amount = 0

        with get_db() as conn:
            ensure_wallet(conn, user["id"])
            wallet = conn.execute(
                "SELECT balance FROM wallets WHERE user_id = ?", (user["id"],)
            ).fetchone()
            if amount <= 0 or not all([account_name, account_number, bank_name]):
                flash("Enter a valid amount and complete your payout details.")
            elif amount > wallet["balance"]:
                flash("Your withdrawal amount is higher than your available balance.")
            else:
                conn.execute(
                    "UPDATE wallets SET balance = balance - ? WHERE user_id = ?",
                    (amount, user["id"]),
                )
                conn.execute(
                    """
                    INSERT INTO withdrawals (user_id, amount, account_name, account_number, bank_name)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (user["id"], amount, account_name, account_number, bank_name),
                )
                conn.commit()
                flash("Withdrawal request submitted successfully.")
                return redirect(url_for("bonuses"))

    with get_db() as conn:
        ensure_wallet(conn, user["id"])
        wallet = conn.execute(
            "SELECT balance, login_bonus_claimed FROM wallets WHERE user_id = ?",
            (user["id"],),
        ).fetchone()
        withdrawals = conn.execute(
            "SELECT * FROM withdrawals WHERE user_id = ? ORDER BY created_at DESC",
            (user["id"],),
        ).fetchall()
        conn.commit()

    return render_template(
        "bonuses.html",
        current_user=user,
        wallet=wallet,
        withdrawals=withdrawals,
    )


init_db()


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5001)
